/* Autogenerated file. Do not edit manually. */

/* tslint:disable */
/* eslint-disable */

/*
  Fuels version: 0.82.0
  Forc version: 0.49.3
  Fuel-Core version: 0.22.1
*/

export type { TokenTrackAbi } from './TokenTrackAbi';

export { TokenTrackAbi__factory } from './factories/TokenTrackAbi__factory';
